ALTER TABLE mentors
    ADD COLUMN IF NOT EXISTS location VARCHAR(120),
    ADD COLUMN IF NOT EXISTS availability VARCHAR(120),
    ADD COLUMN IF NOT EXISTS average_rating DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rating_count INTEGER DEFAULT 0;

ALTER TABLE sessions
    ADD COLUMN IF NOT EXISTS mentor_rating INTEGER,
    ADD COLUMN IF NOT EXISTS rating_feedback TEXT,
    ADD COLUMN IF NOT EXISTS rating_requested_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS rated_at TIMESTAMP;
